Export-YouTube-subscriptions.md
Adds a new article with instructions on how to export your YouTube subscriptions from Google Takeout.
=> Add instructions for exporting YouTube subscriptions

Apache2-Reverse-Proxy.md
Config example with explanation on how to use Apache as Reverse Proxy to add HTTP login over Invidious.
=> Documented HTTP Login with Apache

Installation.md
references [issue #1903](https://github.com/iv-org/invidious/issues/1903)
Revised Docker walkthrough in `Installation.md`
Includes up to date Docker Compose file with Quay image replacing the now-defunct Docker Hub image
Note: In the Docker Compose file, the POSTGRES_USER env var can't be changed because the username `kemal` is hard coded into the initial DB migration files found in `./config/sql/`
=> Add simplified Docker Compose tutorial

Installation.md
Clarify that libpcre and libevent development files are needed for Debian configuration of Invidious.
=> Add missed dependencies for Debian

Invidious-Instances.md
=> Add second instance.

Installation.md
The install.sh script for debian/ubuntu already run `apt update` and `apt install crystal`, so don't tell the user to do it (it will give an error).
=> Fix one-liner crystal install command for debian/ubuntu

Invidious-Instances.md
4 issues about the instance were opened in the last few days:
- https://github.com/iv-org/invidious/issues/2163
- https://github.com/iv-org/invidious/issues/2162
- https://github.com/iv-org/invidious/issues/2161
- https://github.com/iv-org/invidious/issues/2160
I think we should remove it for the moment until the errors are fixed. For example, I just tested, and I can't register on the instance.
@Exonip Could fix the issues on your instance?
=> Remove invidious.exonip.de because it is broken

Installation.md
Make it clear that it requires 2G **free**, not including the kernel and other programs.
See https://github.com/iv-org/invidious/issues/2159#issuecomment-860927228
=> Correct the amount of RAM required for compilation

Invidious-Instances.md
At the time of this PR `invidious.048596.xyz` is running an version from May 13th, 2021 meaning that it is outdated by more than a month. @tenpura-shrimp please update your instance if you would like to remain on the instance list!
=> Remove invidious.048596.xyz | Outdated

Invidious-Instances.md
This is an instance operated by me, the server was donated by someone who would like to stay anonymous.
=> Add invidious-jp.kavin.rocks.

FAQ.md
Update of the answer to the common error: `The media could not be loaded…` now that videos are fetched using the android client.
=> Update answer to `The media could not be loaded…`

Installation.md
This ensures that the exact dependencies versions from shard.lock are used.
See: https://github.com/iv-org/invidious/issues/2918
=> Prefer shards install production

Installation.md
Follow up to https://github.com/iv-org/documentation/pull/160#issuecomment-1039778281
Related to https://github.com/iv-org/invidious/pull/2917 (wait for both to be ready - so that we can merge them at the same time)
Massively enhance the production compose:
- Make the production and development compose use the same (sane and clean) bases
- Change the restart policy for `unless-stopped` since `always` is bad practice
- Remove the network (that's completely useless)
- Remove the resources limiters (that's not really useful, and users should only use it if they need to)
- Remove the `willfarrell/autoheal` container: we can't vouch for it's usefulness, and its security (it has access to the docker socket, which is a massive security risk)
- Bump the postgres version to 14 since it's the …
=> Enhance the production compose file

docs/instances.md
Since I need to rebuild the database therefore its down( it will probably be today and a few days since I don't have much time) and it makes no sense to have a broken instance on that list.
=> Remove instance invidio.xamh.de

docs/installation.md
Newer versions of crystal now works fine: https://github.com/iv-org/invidious/pull/2934
=> Update notice about the required Crystal version

docs/instances.md
instance breaks rule 4 'Instances MUST have an uptime of at least 90% (according to uptime.invidious.io).'
should also be delisted because the instance is down for over a month
https://stats.uptimerobot.com/89VnzSKAn/790590336
in theory the instance could reach 90% at the end of the year if it is going live now but i assume doesnt matter at this point
=> delist invidious.privacy.gd

mkdocs.yml
This PR improves the navigation on the doc in various ways:
- Add structure to the main menu to improve the navigation and readability for users.
- Add the repo_url to mkdocs config. This add a pen icon on each documentation page which redirects to the file in the Github repo.
- Enable the Github logo by adding the repo_url configuration.
- Add a copyright notice to inform that the website content is under CC0 1.0 Universal (CC0 1.0), the license used by this repository.
=> Improve navigation

docs/umatrix.md
Hi. I just moved Invimatrix to Codeberg Pages, as my other projects. I also updated Invimatrix to fix it (I didn't touch it since years, so it was pointing to instances.invidio.us) and to support uBlock Origin rules.
=> Update Invimatrix link

docs/nginx.md
This breaks livestreams and isn't necessary, so remove it.
=> Remove trailing slash from proxy_pass

docs/apache2.md
Adds the bits that are missing (compared to the basic auth config) to the default config.
Also fixes some whitespace/tab issues.
Closes #273
=> Fix apache2 config breaking livestreams

docs/installation.md
The makefile allows us to propose sane defaults without having to change the documentation all the time.
This is a follow-up to iv-org/invidious#3367 and iv-org/invidious#3376
=> Install steps: Prefer `make` over crystal commands

docs/installation.md
I've used `invidious --migrate` multiple times now, and it works very well.
This will prevent problems like https://github.com/iv-org/invidious/issues/3391
=> Install: replace legacy SQL files with --migrate

docs/installation.md
Hey!
After running a public instance for ~2 months, I've noticed that the default docker-based installation doesn't have any limit for the log file size. Invidious logs quite a lot by default, it has generated a few logfiles larger than 10GB on my server.
This MR unifies the logging limits in docker-based installation and the logrotate configuration described in the `Logrotate configuration` documentation section:
- single logfile size limit set to `1G`
- max number of saved log files set to `4`
The configuration was tested on my server and I confirm that its rotating the logs correctly :)
=>  Unify log rotation settings for both docker and manual install

docs/caddy.md, docs/index.md, mkdocs.yml
Hey!
I'm using [Caddy web server](https://caddyserver.com/) as a reverse proxy for my Invidious instance, so I wrote a basic docs page for it. Tried to mimic all the content from Apache and Nginx docs :)
Have a good one!
=> Add Caddy web server reverse proxy documentation

docs/installation.md
The statements are no longer true since the database migrations now reference `current_user` instead of `kemal`.
See also [this comment](https://github.com/iv-org/invidious/pull/1678#discussion_r559189558) pertaining to [this commit](https://github.com/iv-org/invidious/commit/ffa9e5dfab7a1d7ea84d88007107f9f40295c50a).
=> Installation: Remove outdated warning about `$POSTGRES_USER`

docs/instances.md
I have moved the domain of the ``inv.odyssey346.dev`` Invidious instance to ``inv.pistasjis.net``, and I was told to create a PR for this. So, this is that PR.
=> Rename inv.odyssey346.dev instance

docs/applications.md
* Converts all lists in this page to tables.
* Fixes various typos found in the document.
---
* Replaces Roku link for Playlet with one that doesn't require authentication to read.
* Removes Invidition, as the add-on's page literally instructs users to just use Privacy Redirect instead.
* Removes Alternate Tube Redirector, as this has not been maintained in years and was removed from the Mozilla add-on.
* Removes Kodi add-on (by TheAssassin) as this is no longer maintained, repo was archived, and search is broken.
* Renames Another Kodi add-on (by lekma) to just Kodi add-on as this is actively maintained and is far ahead in terms of features compared to the previous one.
---
Preview here:
https://github.com/SethFalco/documentation-1/blob/chore-apps/docs/applications.md
**Ignore …
=> chore: update applications list

docs/installation.md
- Add 1.9.2 as supported crystal version
- Drop crystal versions 1.5.X and 1.4.X 
- Add open sans fonts as dependency
- Remove note about lsquic
Closes #465
=> Update manual install instructions

docs/installation.md
Add two parameters in the post install:
- well known pubsub not documented yet, just found in the config.yml
- the new parameter for bring back the captions: https://github.com/iv-org/invidious/issues/2567
=> Add the new post install parameters

docs/instances.md
Users will be given a two week notice to find another instance and to download their data.
=> Remove vid.priv.au from public instances list

.github/ISSUE_TEMPLATE/new_instance.yaml
After PR #151, the instance rules list was modified to fully ban analytics. The issue template however was never updated.
=> Remove analytics section from issue template

docs/instances.md
removed "* [youtube.owacon.moe](https://youtube.owacon.moe) 🇯🇵  " since the website says that it has been banned from YT everyday. I don't know when but i checked today and that's what the page says.
=> Remove youtube.owacon.moe since instance is banned from YT everyday

docs/applications.md
No apps will be added or reduced. The explanations are also intact.
----
Changes:
**Applications**
* PlasmaTube is developing quickly, so go up. Multi-language is also available.
* Playlet for Roku is for a relatively minor OS, so go down
* Yattee and WatchTube have also in the App Store.
**Browser Extensions**
* Unifies URL usage patterns for Alter, Inviduration
* Add add-on link for Redirector
* Subgrouping tools for redirects
=> applications.md - Various changes and re-order by oldest to newest (for now)

docs/community-installation-guide.md, docs/improve-public-instance.md, docs/installation.md
Using the Trending API by default for health checks is a nice workaround for heath checks failing due to the new comment format. I also imagine that going to the Trending API every 30 seconds might appear to be more normal than getting comments from a specific video every 30 seconds (even if that video is very popular).
_This is a docs PR for: https://github.com/iv-org/invidious/pull/4561_
=> Use trending api for health checks instead of comments

docs/applications.md
Greetings,
I'm the developer of Materialious, a open source interface for Invidious. This PR adds Materialious in the "Lists of third-party projects that use or support Invidious." section of the documentation.
https://github.com/WardPearce/Materialious
=> Add Materialious to third-party projects

docs/api.md, docs/api/authenticated-endpoints.md
These parameters were removed in this PR: https://github.com/iv-org/invidious/pull/4276/
=> API: Remove references to `fields` and `pretty`

docs/api.md
Fix #546
– `type`
– `storyboards`
– `isPostLiveDvr`
– `dashUrl`
=> Add missing properties to /videos API endpoint

.github/ISSUE_TEMPLATE/new_instance.yaml
Instead of asking the user to remind himself to join the public instance maintainers room, we allow the maintainer to specify their matrix username.
When the instance will be accepted, we will add him to the room. Much more simple than asking them to go out of their way to ask us to join the room.
=> Add part for matrix username

docs/improve-public-instance.md
Using http3-proxy returns 403 for video storyboards. After removing `^/sb/` storyboards were able to load.
I did this on my instance and storyboards were able to load without problems and they are now handled by Invidious. Feel free to test it before merging it.
=> Don't use http3-proxy for storyboards.

docs/instances.md
invidious.protokolla.fi has been moved from a German host (Netcup) back to Finland (Hetzner). 
Btw, does this update also the https://api.invidious.io instance list or only the documentation?
=> update invidious.protokolla.fi flag (de -> fi)

docs/instances.md
Remove all instances affected by https://github.com/iv-org/invidious/issues/4734
\+
https://invidious.privacydev.net/ : 504
https://invidious.darkness.services/ : videos just don't play with or without dash
=>  Remove all instances currently broken by the YouTube change (or for a different reason)

docs/nginx.md
Fixed the change of how to enable https on NGinx in newer releases
=> Use the new HTTP2 format for NGINX

docs/url-parameters.md
The documentation has been updated to include the quality_dash preference to enforce preferred quality using dash.
=> Update with all but two URL Parameters

docs/instances.md
Now that Invidious has switched to tagged versioning again, the rule ensuring that instances must not be a month out of date should be updated to support this.
=> Update Rule 2 of instance list

docs/gluetun.md
Same as https://github.com/iv-org/documentation/blob/master/docs/hide-instance-behind-proxy-server.md.
If one wants help for this "official" tutorial, he has to redirect his request to the creator of the article.
=> Add mention about the user that created the doc

.github/ISSUE_TEMPLATE/new_instance.yaml, docs/instances.md
This PR aims to address some issues in the process for proposing a new instance.
1. The existence of the rules for public instances outlined at https://docs.invidious.io/instances/ is unclear. Maintainers are also not explicitly asked to agree to follow these rules.
2. **All external scripts**, not just some, are considered analytics. Ambiguity here may have caused some instances being unnecessarily delisted (see https://github.com/iv-org/documentation/issues/502 and https://github.com/iv-org/documentation/issues/534 for examples).
=> Clarify public instance rules and definition of analytics

docs/instances.md
Domain was changed to https://iv.nowhere.moe/
=> Restore iv.datura.network instance

docs/installation.md
Thanks to two different users that made me realise that it was out of sync with our CI test matrix (version 1.8 and before fail due to the missing `String.match!()` function in the stdlib)
=> Update supported Crystal versions in "installation.md"

docs/gluetun.md, docs/index.md, mkdocs.yml
This adds back gluetun to the home page until http_proxy feature is merged into the Invidious core.
=> add back gluetun with warning until http_proxy feature merged

docs/installation.md
Added an example service file with strict security options - as strict as systemd lets you go, I hope. `systemd-analyze security` of systemd 256 rates this configuration with an exposure level of 1.1 OK, where 9.2 UNSAFE is the default. The service can be further locked down with `RootDirectory`, but that requires setting up a chroot, so I opted to omit it.
=> Add an example systemd service file for inv_sig_helper

docs/community-installation-guide.md
This adds a completely new chapter on podman quadlet installation method. This is emerging technology which is now available in Fedora and being backported into CentOS 9 Stream. These days I deploy pretty much everything using this technique and all users familiar with systemd can easily manage such deployments. All containers in the setup are root-less, work under SELinux enforcing mode and integrates with systemd nicely including logging or health checks.
=> Add podman quadlet installation method

docs/applications.md
A friend suggested that I PR it here. I've had this project running for a while; it's a way to avoid loading the YouTube embed along with all the tracking and ads that come with it—primarily on Discord but also potentially on other apps. It's about as privacy-respecting as it can be while running on Cloudflare's servers, but I think it still fits the applications doc.
Let me know if you'd rather not have the links populated like that for consistency.
=> Applications: add Koutube

docs/installation.md
Just added a comma to fix a grammar issue: `Because of various issues**,** Invidious must be restarted often, at least once a day, ideally every hour.`
=> Added comma to fix grammar

docs/instances.md
Invidious instances-api requires a scheme for each and every single URL or else the entire fetch logic will raise and prevent the instances list from getting updated.
This is especially noticeable on a restart where there isn't a previous list to fallback to and as such the instances api will remain an empty list.
=> Add scheme to url for invidious.schenkel.eti.br

docs/companion-apache2.md
in matrix an user encountered errors with the apache2 config for the companion setup, this adjusts the correct ports for the companion, like it is done in the other configs: caddy, nginx, traefik
=> Fix companion port 8282 for companion-apache2

docs/instances.md
I2P URL has been updated to the new working one.
mCaptcha has been disabled for now and replaced by Anubis, this may change in the future, but now it's like this.
=> Update inv.nadeko.net instance information

docs/companion-traefik.md
Following https://github.com/iv-org/documentation/issues/665
https://github.com/iv-org/invidious-companion/wiki/How-to-communicate-with-Invidious-companion-with-any-client-(HTTP-API) says `/companion` is only the beginning of the API paths, not the full path
=> Traefik reverse-proxy rule update: Path -> PathPrefix

docs/companion-caddy.md
The url matcher should include a wildcard.
Cf https://caddyserver.com/docs/caddyfile/matchers#syntax.
Successfully fixed my production configuration, allowing me to download the videos.
=> Fix companion caddy configuration
