Invidious-Instances.md

add my instance

---

Invidious-Instances.md

Also add the country flag of the onion since:
- I do not care about the anonymity of this hidden service.
- YouTube sensor some video depending of the country, so it is interesting to know which country is used to connect to YouTube.

doc: add my onion instance

---

Invidious-Instances.md

Stop listing it and see what happens with the load

Comment out instance

---

Invidious-Instances.md

Reverts iv-org/documentation#10

Revert "Comment out instance"

---

Invidious-Instances.md

Add the instance vid.puffyan.us and its onion address

Add vid.puffyan.us and its onion

---

Invidious-Instances.md

Add shield.io to ytprivate.com

---

Invidious-Instances.md

Requested by johackim via email.

Add ethibox instance

---

Invidious-Instances.md

added my instance, invidious.himiko.cloud.

Add invidious.himiko.cloud

---

HOME.md
Installation.md

Related https://github.com/iv-org/invidious/pull/1807
Also add "Because of various issues Invidious **must** be restarted often, at least once a day, ideally every hours." to the post-install instruction.

Move some readme content, and enhance some things

---

Invidious-Instances.md

I use it. I am aware that it goes off intermittently (Once or twice a day, ~5 minutes each) but it is mostly online.
cc @tenpura-shrimp . Also, (I think you own the instance?) you need to update it to fix the channel page problem.

Bring back invidious.048596.xyz

---

Invidious-Instances.md

https://invidious.silkky.cloud
hosted in Finland on a dedicated server.
Mozilla observatory: https://observatory.mozilla.org/analyze/invidious.silkky.cloud

Add invidious.silkky.cloud

---

Invidious-Instances.md

New instance added: https://notyoutube.org. (line 58 and 59)

Update invidious-instances.md (New instance added)

---

Invidious-Instances.md

I did not expect the huge amount of traffic I would gain from this. My VPS cannot handle the amount of bandwidth it is using.

Remove instance

---

Installation.md

Precise clearly how to install the crystal version required by invidious on Archlinux.

Provide a more precise install guide for Archlinux

---

Configuration.md

Replace `config/config.yaml` with `config/config.example.yml`

Update link to config file in source code

---

Invidious-Instances.md

Add https://invidious.moomoo.me/
Please let me know if there's anything else I need to do.
I have a crontab to autoupdate.

Add invidious.moomoo.me

---

Invidious-Instances.md

I’m not using uptime robot anymore and therefore the description doesn’t fit

Update status page of invidious.exonip.de

---

Invidious-Instances.md

https://notyoutube.org/ last updated on May 4th 2021
https://invidious.blamefran.net/ last updated on May 9th 2021
@dejalavidavolar @Aidan16 If you would like to get added back onto the instance list, please make sure that you're able to maintain it!

Remove outdated instances

---

Invidious-Instances.md

Add ytb.trom.tf to instances list

---

Invidious-Instances.md

Add the instance invidious.exonip.de again after issues have been fixed and link to changed css

Add instance invidious.exonip.de back

---

Invidious-Instances.md

Add  y.com.cm to instance list

---

Invidious-Instances.md

adds instance [invidious.cmh.pw](https://invidious.cmh.pw), usa, using cloudflare, uptime robot shield.

add invidious.cmh.pw

---

Invidious-Instances.md

This reverts commit d17436a96e6dd0386f0515fac647940311d1cd13.
[Instance has been updated](https://github.com/iv-org/documentation/pull/94#issuecomment-871171098)

Revert "Remove ytprivate.com | Broken + Outdated (#94)"

---

Invidious-Instances.md

wasnt quite ready for this to be public yet, please revert this & https://github.com/iv-org/documentation/pull/76/commits/4fb46a79b55121ca97eba5584364a3d6e967be55
Thanks:)

backpedal on my instance

---

Invidious-Instances.md

Invidious instance operated with Yunohost

Adding my UK Instance

---

Invidious-Instances.md

Adding more info for ytb.trom.tf

Adding more info for ytb.trom.tf

---

Invidious-Instances.md

Closes #119
Nb: From what I found, it doesn't seem to use anything like CF. @TechnicalSuwako can you please confirm?

Add instance youtube.076.ne.jp

---

Invidious-Instances.md

https://stats.uptimerobot.com/89VnzSKAn/788276049
@Aidan16

Remove invidious.blamefran.net | Poor uptime

---

Installation.md

Counterpart of https://github.com/iv-org/invidious/pull/2296

Docker-compose: use POSTGRES_USER variable in `healthcheck`

---

Invidious-Instances.md

Instance hasn't been updated since July 16th, 2021.
@tomaytotomato Please update your instance or we'll be forced to remove it.

Remove invidious.noho.st | Outdated

---

Invidious-Instances.md

Instance is down, status page loads indefinitely.

Remove instance invidious.s1gm4.eu

---

Invidious-Instances.md

See https://github.com/iv-org/invidious-redirect/issues/12#issuecomment-909819684
Reverts iv-org/documentation#134

Revert "Remove ytprivate.com (outdated)" | Instance has been updated with changes stated again

---

Invidious-Instances.md

We have reinstated our Invidious instance and implemented AntiCaptcha! Here's a commit so you can reinstate it into the instance list.

Added vid.mint.lgbt back! (yes it's back)

---

Invidious-Instances.md

I moved the server to the Netherlands, I added a link to the Status page.

invidious.hub.ne.kr

---

Installation.md

Follow up to https://github.com/iv-org/invidious/pull/2490

Fix `Role "kemal" does not exist`

---

Invidious-Instances.md

It's hasn't been a month, but the instance is properly updated and respects all the requirements, so we can add it now.
Please @cysea confirm that the instance is ready to be added to the instances list.
Note: One issue I can see is that your fork is based on @unixfox work, that isn't released under an open source license. So he might not necessarily be okay with that.

Add inv.cthd.icu (Closes #156)

---

Apache2-reverse-proxy.md

Apache sample config

---

Invidious-Instances.md

Closes #153
(NB: placed before inv.cthd.icu to respect addition requests' chronological order)

Add invidious.mutahar.rocks to the instance list

---

Extensions.md

Update Extensions.md: Alter

---

Invidious-Instances.md

Instance has been dead for a month: https://stats.uptimerobot.com/89VnzSKAn/789232279

Remove yt.didw.to

---

Invidious-Instances.md

Fixes https://github.com/iv-org/documentation/issues/181

Remove vid.mint.lgbt

---

Invidious-Instances.md

Waiting on https://github.com/iv-org/documentation/issues/180#issuecomment-1032743898

Add invidious.flokinet.to (Closes #180)

---

Invidious-Instances.md

Add invidious.privacy.gd

---

Invidious-Instances.md

Migrate inv -> tube.cthd.icu

---

home.md

Remove link to "Updating.md"

---

Invidious-Instances.md

Fixes https://github.com/iv-org/documentation/issues/183

Add invidious.weblibre.org

---

Invidious-Instances.md

Fixes https://github.com/iv-org/documentation/issues/190
The instance has not yet been running for 30 days, only 26 days, but the maintainer claim on the 5th February that it has been running for 2 months and the uptime seems great.

Add invidious.esmailelbob.xyz

---

docs/Invidious-Instances.md

Add max16k.invidious.icu

---

docs/Invidious-Instances.md

Add invidious.mutahar.rocks and inv.bp.mutahar.rocks

---

docs/Invidious-Instances.md

Fixes https://github.com/iv-org/documentation/issues/197#issuecomment-1074489268

Update the domain name of max16k.invidious.icu to invidious.lunar.icu

---

docs/FAQ.md

Answer the following frequently asked questions:
- Can't login nor save preferences (e.g #2962)
- Sync user data between multiple instances (e.g #2515)
- Captions/Subtitles not showing up (e.g #2565)
- DB::PoolRetryAttemptsExceeded (e.g #1582)
- Where are the other quality options? (e.g #2521)
Closes #163

Add some answers to the FAQ

---

docs/instances.md

From https://github.com/iv-org/documentation/issues/222
Instance already got the good uptime: https://stats.uptimerobot.com/89VnzSKAn/788466073
Closes https://github.com/iv-org/documentation/issues/222

Add y.com.sb

---

docs/instances.md

Update the domain name of inv.bp.mutahar.rocks to inv.bp.projectsegfau.lt

---

docs/instances.md

inv.bp.projectsegfau.lt moved to Greece

---

docs/instances.md

I'll be shutting down my US instance since I don't have enough time to give to maintain it, I will be converting this server to host Piped instead on the 15th.

Remove invidious-us.kavin.rocks.

---

docs/instances.md

Closes https://github.com/iv-org/documentation/issues/225

Add invidious.tiekoetter.com

---

docs/instances.md

Closes https://github.com/iv-org/documentation/issues/241

Add invidious.nerdvpn.de

---

docs/instances.md

Closes https://github.com/iv-org/documentation/issues/244

Add inv.vern.cc

---

docs/instances.md

* [invidious.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion](http://invidious.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion) 🇨🇦 (Onion of invidious.esmailelbob.xyz)

add onion for invidious.esmailelbob.xyz

---

docs/instances.md

Instance has been down for 5 days, from: https://lunar.icu/ "We are stopping our service."

Remove invidious.lunar.icu

---

docs/instances.md

Closes https://github.com/iv-org/documentation/issues/245

Add invidious.slipfox.xyz

---

docs/instances.md

Closes https://github.com/iv-org/documentation/issues/260

Add inv.privacy.com.de

---

docs/instances.md

this updates the flags of the Project Segfault instances to reflect changes in hosting.
Please merge whenever you feel like it.

update flags for Project Segfault Invidious instances.

---

docs/instances.md

Add invidious.rhyshl.live

---

docs/installation.md

Note: I'm not sure 1GB of ram is enough to run Invidious

Update the hardware requirements

---

docs/instances.md

This PR adds an I2P instance list along with ~vern's eepsite

Add an I2P section to the instance list and add ~vern's invidious eepsite to it

---

docs/url-parameters.md

The URL Parameter for disabling comments has been added.
I encourage anyone and anyone to request Pull Requests with any additional URL Parameters missing.

"Comments" added to URL-Parameters.md

---

docs/applications.md

Redirector was added to the list of extensions, with instructions to read Redirector_Setup for more information.

Redirector added to Extensions list

---

docs/api/channels_endpoint.md
docs/api/common_types.md

this PR documents the change from the following PRs:
- https://github.com/iv-org/invidious/pull/3625
- https://github.com/iv-org/invidious/pull/3626

Api docs update

---

docs/applications.md

Add [Playlet](https://github.com/iBicha/playlet) to the list of applications
(You can see it in action here [video](https://youtu.be/qmSvA-QQW20))

Add Playlet to the list applications

---

docs/applications.md

Added the following Tampermonkey Scripts: Simple Sponsor Skipper, Privacy Redirector.

Add Tampermonkey Scripts.

---

docs/export-youtube-subscriptions.md

It took me like 10 minutes to figure out that I had the wrong account selected, so here is a warning for the next guy.

Add into about multiple accounts to subscription export

---

.github/ISSUE_TEMPLATE/new_instance.yaml

In order to not having a case like this again: https://github.com/Sommerwiesel/invidious/issues/6#issuecomment-1337036938

Add mandatory unlimited traffic limit

---

docs/instances.md

See: https://github.com/iv-org/documentation/issues/371

Add onion of vid.priv.au

---

docs/instances.md

Closes #395 
My LGBT a** won't accept that.

Remove esmailelbob.xyz for hateful TOS update

---

docs/instances.md

Related to https://github.com/iv-org/documentation/pull/396
I personally want instances owners to be able to block juridical person if they want to, but natural person (i.e Humans) shouldn't be blocked for any reason.

Add a new rule about access restriction

---

docs/instances.md

See https://github.com/iv-org/documentation/pull/397#issuecomment-1556271233

Reword note under instance rules

---

docs/api/channels_endpoint.md
docs/api/common_types.md

Relies on https://github.com/iv-org/invidious/pull/3767 to be merged

Add playlist attachment type

---

docs/installation.md

Need to fix manual update instruction on 263 line

Update command for switching to invidious user

---

docs/installation.md

See https://github.com/iv-org/invidious/pull/3955

Install: Add 'hmac_key' to docker-compose

---

docs/installation.md

It's causing too many issues and wasting our time.
https://github.com/iv-org/invidious/issues/3985
And more issues if you search in the issues tracker

Remove automated docker install

---

docs/instances.md

Tor: http://inv.zzlsghu6mvvwyy75mvga6gaf4znbp3erk5xwfzedb4gg6qqh2j6rlvid.onion
I2P B32:  zzlsbhhfvwg3oh36tcvx4r7n6jrw7zibvyvfxqlodcwn3mfrvzuq.b32.i2p
I2P Domain: inv.zzls.i2p
I2P Address Helper: [Link too long, click here](http://inv.zzls.i2p/?i2paddresshelper=DEmWmD21XUxpD02quCnDreZMS80OWjHOFi0VfGu7aZir5wNlgfhmsd5-tM-zAyUBgYzp9iiP4Ot8ngD~1r~2EpZw2yxoSkfPJuDu6ZnXMd76m1NFEfsBrF6UD6ftzzinJjCovjDx6X4wkHsuXQkAGTexOY20Q7SRtcoGTzTSaS5r9ieAv0wLhk0~nMlN--8EsG7FPJViMHm1JXZeGgpVfJ4LnqSlp2SjI7NF7rzduoN8LrO36MJgslE4aoqkbL9f6kfnqxQN9pBOXZElfsnEGiEuH18P598iq6u2H-t5zFTnfCuljgONG4EKPw3bX9e61TCQyY8ktjmJ7xaF-N1h2uyEMtU2Gw18wMW~oSh133uT5VOaNvJSMHldVzCTT-Jh7IQy1TYbDXzAxb-hKHXfe5PlU5o28lIweV1XMJNP4mGDvRTDNhsNfMDFv6Eodd97k-VTmjbyUjB5XVcwk0~iYRNTnL3~jVdBHRhzXsQzeoHw0AP3Yg2RBP8vt10y2zgqBQAEAAcAAA==)
I tested and …

Add I2P and Tor addresses for inv.zzls.xyz

---

docs/instances.md

Remove https://invidious.0011.lt as per maintainer request

---

docs/index.md
docs/ipv6-rotator.md
mkdocs.yml

Documentation for this project: https://github.com/iv-org/smart-ipv6-rotator

add documentation for ipv6 rotator

---

docs/improve-public-instance.md

`Scale` can be replaced with `deploy.replicas` within the compose file.
https://github.com/docker/compose/issues/5586#issuecomment-972130556
Using a variable in proxy_pass forces re-resolution of the DNS names. (In my tests, this helps solving some network quirks)
https://forum.nginx.org/read.php?2,215830,215832#msg-215832

Use deploy.replicas and variable in proxy_pass in improve-public-instance.md

---

docs/applications.md

Taken from https://github.com/iv-org/invidious/pull/4283 / https://github.com/iv-org/invidious/pull/3853

Add list of applications using Invidious

---

docs/instances.md

Tor address changed too, I2P for later.

inv.zzls.xyz -> inv.nadeko.net

---

docs/instances.md

There are many Tor onion instances that no longer exist. Tested using Tor Browser .

Prune onion instances

---

docs/instances.md

Creating a custom onion domain for my invidious instance: invidious.nerdvpn.de.

Update onion instance of invidious.nerdvpn.de

---

docs/instances.md

Change iv.datura.network from Germany to Finland

---

docs/instances.md

Change invidious.nerdvpn.de from Germany to Ukraine

---

docs/instances.md

Change country of iv.nboeck.de to Germany

---

docs/instances.md

Add invidious.privacyredirect.com

---

.github/workflows/add-instance-updown.yml

Using the same CI file as uptimerobot (so that it can be removed easily when we dump uptimerobot)
The only things I changed are from line 53 to 63
https://updown.io/api#POST-/api/checks

Add a CI to add instances to updown

---

docs/installation.md

Some things I noticed while running through this for the first time.

Update macOS install

---

docs/instances.md

Remove instance inv.oikei.net

---

docs/instances.md

Add inv.in.projectsegfau.lt to the instance list

---

docs/instances.md

Add invidious.incogniweb.net to the instance list

---

docs/register-user.md
docs/reset-password.md
mkdocs.yml

Trying https://github.com/iv-org/documentation/pull/458 again.

Doc: Add scripts for manual registration + improve manual reset password

---

docs/instances.md

Instanced updated to support the new workarounds

Add back inv.tux.pizza

---

docs/applications.md

I hope you'll appreciate it, I'd be happy to see my little project there :)

Applications: add IInvidious

---

docs/instances.md

I recently added a antibot captcha to my instance which is the rule 8 in https://docs.invidious.io/instances/#rules-to-have-your-instance-in-this-list
This captcha is only triggered against abusive IPs that exceed the rate limits that I currently have (mostly chinese IPs, alibaba cloud, etc).
It can be resolved without JavaScript using https://mcaptcha.org/docs/user-manual/how-to-mcaptcha-without-js
Feel free to edit `mCaptcha` to something that fits more closely with what I did with my instance.
https://github.com/user-attachments/assets/0bba9dfb-068f-417e-837a-b923bbf51a7d

Update inv.nadeko.net instance details

---

docs/instances.md

causes "mCaptcha" to show up as a instance on api.invidious.io

remove mCaptcha hyperlink

---

docs/installation.md

Integrate the change from iv-org/inv_sig_helper@215d32c so that the inv_sig_helper container responds to SIGTERM.

Add init to inv_sig_helper entry in docker-compose.yml

---

docs/faq.md
docs/youtube-errors-explained.md
mkdocs.yml

Document all the possible YouTube errors with solutions.
This is quite urgent because stable release will have this documentation linked when an error is given by the Invidious frontend.

document youtube errors with solutions

---

docs/api.md
docs/api/channels_endpoint.md
docs/api/common_types.md

Fix various api documentation issues

---

docs/youtube-errors-explained.md

Changing sent to send in the youtube-errors-explained page

Small grammar correction

---

docs/companion-apache2.md
docs/companion-caddy.md
docs/companion-installation.md
docs/companion-nginx.md
docs/index.md
docs/invidious-companion.md
mkdocs.yml

Mainly based from https://github.com/iv-org/documentation/pull/610
Close #610

add invidious companion temporary doc

---

docs/companion-installation.md
docs/companion-traefik.md

Haii there ^^
Here is how I made the companion work with Traefik.
The PR is based on the Caddy page of #620
Also, please let me know if anything needs to be clearer or explained more.

Add Traefik configuration to Invidious Companion doc

---

docs/applications.md

Playlet url: locale in url not needed

[applications.md] small tweak in app url

---

docs/instances.md

Saw this on the page and it felt a little off. Maintainers can close the request if they feel so, I just thought I'd make a PR anyway

Update instances.md grammar

---

docs/installation.md

Invidious uses "CHANGE_ME!!" instead of "CHANGE_ME" to warn users that a config option must be changed

Set CHANGE_ME to CHANGE_ME!! in example compose
